#_author_:zhangsx

Feature:当前子账号使用情况
  子账号上限为50，已使用数与剩余数相加为50
Background:
    Given jobs登录系统
    And jobs已添加角色信息
        """
        [{
            "role_name":"角色0",
            #"button":"添加权限",
            "permissions":
            [{
                "type":""，
                "value":
                [{
                    "name":"暂未给此角色添加权限"
                }]
            }]
        },{
            "role_name":"角色1",
            #"button":"修改权限",
            "permissions":
            [{
                "type":"商品管理"，
                "value":
                    [{
                        "name":"添加新商品",
                        "name":"在售商品管理",
                        "name":"待售商品管理"
                    }]
            }]
        },{
            "role_name":"角色2",
            #"button":"修改权限",
            "permissions":
                [{
                    "type":"商品管理"，
                    "value":
                    [{
                        "name":"添加新商品"
                    }]
                },{
                    "type":"促销管理"，
                    "value":
                    [{
                        "name":"促销查询",
                        "name":"限时抢购"
                    }]
                },{
                    "type":"配置管理"，
                    "value":
                    [{
                        "name":"运费模板",
                        "name":"物流名称管理",
                        "name":"支付方式"
                    }]
                }]
        }]
        """
    And jobs已添加部门
        """
        [{
            "department_name":"部门1"
        }]
        """
    And jobs已获取员工信息列表
        """
        [{
             "reminder":"",
            "employees":
            [{
                "account_name":"ceshi02",
                "employee_name":"张02",
                "department_name":"部门1",
                "roles":"角色1",
                "is_active":"启用"
            ]
        },{
            "reminder":"",
            "employees":
            [{
                "account_name":"ceshi01",
                "employee_name":"张01",
                "department_name":"部门1",
                "roles":"角色0",
                "is_active":"启用"
            }]
        },{
            "reminder":"",
            "employees":
            [{
                "account_name":"ceshi00",
                "employee_name":"张00",
                "department_name":"部门1",
                "roles":"",
                "is_active":"启用"
            }]
        }]
        """
Scenario:1 当前子账号使用情况
    When jobs访问账号帮助
    Then jobs显示当前子账号使用情况
        """
        [{
            "used":3,
            "remain":47
        }]
        """
    When jobs新建员工
        """
        [{
            "employees":
            [{
                "account_name":"ceshi03",
                "password":"123456a",
                "confirm_password":"123456a",
                "employee_name":"张03",
                "department_name":"部门1"
            }]
        "roles":
            [{
                "role_name":"角色0",
                "is_selected":"Y"
            },{
                "role_name":"角色1",
                "is_selected":"N"
            },{
                "role_name":"角色2",
                "is_selected":"Y"
            }]
        "permissions":
            [{
                "presentation":"",
                [{
                    "type":"商品管理",
                    "value":
                    [{
                        "name":"添加新商品"
                    }]
                },{
                    "type":"促销管理",
                    "value":
                    [{
                        "name":"促销查询",
                        "name":"限时抢购"
                    }]
                },{
                    "type":"配置管理",
                    "value":
                    [{
                        "name":"运费模板",
                        "name":"物流名称管理",
                        "name":"支付方式"
                    }]
                }]
            }]
        }]
        """
    Then jobs获取员工信息列表
        """
        [{
            "reminder":"",
            "employees":
            [{
                "account_name":"ceshi03",
                "employee_name":"张03",
                "department_name":"部门1",
                "roles":"角色0及其他",
                "is_active":"启用"
            }]
        },{
            "reminder":"",
            "employees":
            [{
                "account_name":"ceshi02",
                "employee_name":"张02",
                "department_name":"部门1",
                "roles":"角色1",
                "is_active":"启用"
            }]
        },{
            "reminder":"",
            "employees":
            [{
                "account_name":"ceshi01",
                "employee_name":"张01",
                "department_name":"部门1",
                "roles":"角色0",
                "is_active":"启用"
            }]
        },{
            "reminder":"",
            "employees":
            [{
                "account_name":"ceshi00",
                "employee_name":"张00",
                "department_name":"部门1",
                "roles":"",
                "is_active":"启用"
            }]
        }]
        """
    When jobs访问账号帮助
    Then jobs显示当前子账号使用情况
        """
        [{
            "used":4,
            "remain":46
        }]
        """
