#_author_:zhangsx

Feature:员工管理-新建员工(新建、启停用员工、删除、子账号上限50)
    1.新建员工必填字段：账户名称、密码、确认密码、员工姓名、部门
    2.字符限制：
    账号名称：用户登陆的账号，用户名一旦注册不能更改，4-20位字符，
            可使用汉字、字母或数字的组合，不建议使用纯数字
    密码：6-20位字符，可使用字母、数字或符号的组合，不建议使用单一类型
    3.角色：每个子账号可以选择多个角色，甚至全部角色
    4.子账号上限为50（若达到50个子账号后再添加新的子账号时提示：“已达到子账号最大限额（50）”）
    5.启用和停用子账号
    6.删除员工
Background:
    Given jobs登录系统
    And jobs已添加角色信息
        """
        [{
            "role_name":"角色0",
            #"button":"添加权限",
            "permissions":
                [{
                    "type":""，
                    "value":
                    [{
                        "name":"暂未给此角色添加权限"
                    }]
                }]
        },{
            "role_name":"角色1",
            #"button":"修改权限",
            "permissions":
            [{
                "type":"商品管理"，
                "value":
                    [
                        {"name":"添加新商品"},
                        {"name":"在售商品管理"},
                        {"name":"待售商品管理"}
                    ]
            }]
        },{
            "role_name":"角色2",
            #"button":"修改权限",
            "permissions":
                [{
                    "type":"商品管理"，
                    "value":
                    [{
                        "name":"添加新商品"
                    }]
                },{
                    "type":"促销管理"，
                    "value":
                    [
                        {"name":"促销查询"},
                        {"name":"限时抢购"}
                    ]
                },{
                    "type":"配置管理"，
                    "value":
                    [
                        {"name":"运费模板"},
                        {"name":"物流名称管理"},
                        {"name":"支付方式"}
                    ]
                }]
        }]
        """
Scenario:1 新建员工
#未创建部门、新建员工
    When jobs新建员工
    Then jobs提示错误信息'请先创建部门再新建员工'

#已创建部门、新建员工
    Given jobs已新建部门
        """
        [{
            "department_name":"部门1",
            "reminder":"还没有员工，请添加",
            "employees":
            [{
                "account_name":"",
                "employee_name":"",
                "deparment_name":"",
                "roles":"",
                "is_active":""
            }]
        }]
        """
    #1新建员工-不设置角色（空）
        When jobs新建员工
            """
            [{
                "employees":
                [{
                    "account_name":"ceshi00",
                    "password":"123456a",
                    "confirm_password":"123456a",
                    "employee_name":"张00",
                    "department_name":"部门1"
                }]
                "roles":
                [{
                    "role_name":"角色0",
                    "is_selected":"N"
                },{
                    "role_name":"角色1",
                    "is_selected":"N"
                },{
                    "role_name":"角色2",
                    "is_selected":"N"
                }]
                "permissions":
                [{
                    "presentation":"此员工未设置权限",
                    "type":"",
                    "values":""
                }]
            }]
            """
        Then jobs获取员工信息列表
            """
            [{
                "reminder":"",
                "employees":
                [{
                    "account_name":"ceshi00",
                    "employee_name":"张00",
                    "department_name":"部门1",
                    "roles":"",
                    "is_active":"启用"
                }]
            }]
            """
    #2新建员工-设置一个角色（角色0），该角色未设置权限
        When jobs新建员工
            """
            [{
                "employees":
                [{
                    "account_name":"ceshi01",
                    "password":"123456a",
                    "confirm_password":"123456a",
                    "employee_name":"张01",
                    "department_name":"部门1"
                }]
                "roles":
                [{
                    "role_name":"角色0",
                    "is_selected":"Y"
                },{
                    "role_name":"角色1",
                    "is_selected":"N"
                },{
                    "role_name":"角色2",
                    "is_selected":"N"
                }]
                "permissions":
                [{
                    "presentation":"",
                    "type":"",
                    "values":""
                }]
            }]
            """
        Then jobs获取员工信息列表
            """
            [{
                "reminder":"",
                "employees":
                [{
                    "account_name":"ceshi01",
                    "employee_name":"张01",
                    "department_name":"部门1",
                    "roles":"角色0",
                    "is_active":"启用"
                },{
                    "account_name":"ceshi00",
                    "employee_name":"张00",
                    "department_name":"部门1",
                    "roles":"",
                    "is_active":"启用"
                }]
            }]
            """
    #3新建员工-设置一个角色（角色1），该角色设置权限
        When jobs新建员工
            """
            [{
                "employees":
                [{
                    "account_name":"ceshi02",
                    "password":"123456a",
                    "confirm_password":"123456a",
                    "employee_name":"张02",
                    "department_name":"部门1"
                }]
                "roles":
                [{
                    "role_name":"角色0",
                    "is_selected":"N"
                },{
                    "role_name":"角色1",
                    "is_selected":"Y"
                },{
                    "role_name":"角色2",
                    "is_selected":"N"
                }]
                "permissions":
                [{
                    "presentation":"",
                    "type":"商品管理"，
                    "value":
                    [
                        {"name":"添加新商品"},
                        {"name":"在售商品管理"},
                        {"name":"待售商品管理"}
                    ]
                }]
            }]
            """
        Then jobs获取员工信息列表
            """
            [{
                "reminder":"",
                "employees":
                [{
                    "account_name":"ceshi02",
                    "employee_name":"张02",
                    "department_name":"部门1",
                    "roles":"角色1",
                    "is_active":"启用"
                },{
                    "account_name":"ceshi01",
                    "employee_name":"张01",
                    "department_name":"部门1",
                    "roles":"角色0",
                    "is_active":"启用"
                },{
                    "account_name":"ceshi00",
                    "employee_name":"张00",
                    "department_name":"部门1",
                    "roles":"",
                    "is_active":"启用"
                }]
            }]
            """
    #4新建员工-设置多个角色（角色0、角色2）
        When jobs新建员工
            """
            [{
                "employees":
                [{
                    "account_name":"ceshi03",
                    "password":"123456a",
                    "confirm_password":"123456a",
                    "employee_name":"张03",
                    "department_name":"部门1"
                }]
                "roles":
                [{
                    "role_name":"角色0",
                    "is_selected":"Y"
                },{
                    "role_name":"角色1",
                    "is_selected":"N"
                },{
                    "role_name":"角色2",
                    "is_selected":"Y"
                }]
                "permissions":
                [{
                    "presentation":"",
                    [{
                        "type":"商品管理"，
                        "value":
                        [{
                            "name":"添加新商品"
                        }]
                    },{
                        "type":"促销管理"，
                        "value":
                        [
                            {"name":"促销查询"},
                            {"name":"限时抢购"}
                        ]
                    },{
                        "type":"配置管理"，
                        "value":
                        [
                            {"name":"运费模板"},
                            {"name":"物流名称管理"},
                            {"name":"支付方式"}
                        ]
                    }]
                }]
            }]
            """
        Then jobs获取员工信息列表
            """
            [{
                "reminder":"",
                "employees":
                [{
                    "account_name":"ceshi03",
                    "employee_name":"张03",
                    "department_name":"部门1",
                    "roles":"角色0及其他",
                    "is_active":"启用"
                },{
                    "account_name":"ceshi02",
                    "employee_name":"张02",
                    "department_name":"部门1",
                    "roles":"角色1",
                    "is_active":"启用"
                },{
                    "account_name":"ceshi01",
                    "employee_name":"张01",
                    "department_name":"部门1",
                    "roles":"角色0",
                    "is_active":"启用"
                },{
                    "account_name":"ceshi00",
                    "employee_name":"张00",
                    "department_name":"部门1",
                    "roles":"",
                    "is_active":"启用"
                }]
            }]
            """
    #5新建员工-设置全部角色（角色0、角色1、角色2）
        When jobs新建员工
            """
            [{
                "employees":
                [{
                    "account_name":"ceshi04",
                    "password":"123456a",
                    "confirm_password":"123456a",
                    "employee_name":"张04",
                    "department_name":"部门1"
                }]
                "roles":
                [{
                    "role_name":"角色0",
                    "is_selected":"Y"
                },{
                    "role_name":"角色1",
                    "is_selected":"Y"
                },{
                    "role_name":"角色2",
                    "is_selected":"Y"
                }]
                "permissions":
                [{
                    "presentation":"",
                    [{
                        "type":"商品管理"，
                        "value":
                        [{
                            "name":"添加新商品"
                        }]
                    },{
                        "type":"促销管理"，
                        "value":
                        [
                            {"name":"促销查询"},
                            {"name":"限时抢购"}
                        ]
                    },{
                        "type":"配置管理"，
                        "value":
                        [
                            {"name":"运费模板"},
                            {"name":"物流名称管理"},
                            {"name":"支付方式"}
                        ]
                    },{
                        "type":"商品管理"，
                        "value":
                        [
                            {"name":"添加新商品"},
                            {"name":"在售商品管理"},
                            {"name":"待售商品管理"}
                        ]
                    }]
                }]
            }]
            """
        Then jobs获取员工信息列表
            """
            [{
                "reminder":"",
                "employees":
                [{
                    "account_name":"ceshi04",
                    "employee_name":"张04",
                    "department_name":"部门1",
                    "roles":"角色0及其他",
                    "is_active":"启用"
                },{
                    "account_name":"ceshi03",
                    "employee_name":"张03",
                    "department_name":"部门1",
                    "roles":"角色0及其他",
                    "is_active":"启用"
                },{
                    "account_name":"ceshi02",
                    "employee_name":"张02",
                    "department_name":"部门1",
                    "roles":"角色1",
                    "is_active":"启用"
                },{
                    "account_name":"ceshi01",
                    "employee_name":"张01",
                    "department_name":"部门1",
                    "roles":"角色0",
                    "is_active":"启用"
                },{
                    "account_name":"ceshi00",
                    "employee_name":"张00",
                    "department_name":"部门1",
                    "roles":"",
                    "is_active":"启用"
                }]
            }]
            """
    #6校验账户名称重复（账户名称相同、员工姓名不同）
        When jobs新建员工
            """
            [{
                "employees":
                [{
                    "account_name":"ceshi00",
                    "password":"123456a",
                    "confirm_password":"123456a",
                    "employee_name":"张李",
                    "department_name":"部门1"
                }]
                "roles":
                [{
                    "role_name":"角色0",
                    "is_selected":"N"
                },{
                    "role_name":"角色1",
                    "is_selected":"N"
                },{
                    "role_name":"角色2",
                    "is_selected":"N"
                }]
                "permissions":
                [{
                    "presentation":"此员工未设置权限",
                    "type":"",
                    "values":""
                }]
            }]
            """
        Then jobs提示错误信息'该子账号已被使用'
    #7必填字段的校验（账户名称、密码、确认密码、姓名和部门）
        When jobs新建员工
        """
        [{
            "employees":
            [{
                "account_name":"",
                "password":"",
                "confirm_password":"",
                "employee_name":"",
                "department_name":""
            }]
        "roles":
            [{
                "role_name":"角色0",
                "is_selected":"N"
            },{
                "role_name":"角色1",
                "is_selected":"N"
            },{
                "role_name":"角色2",
                "is_selected":"N"
            }]
        "permissions":
            [{
                "presentation":"此员工未设置权限",
                "type":"",
                "values":""
            }]
        }]
        """
        Then jobs提示错误信息'账户名称4-20位字符'
        And jobs提示错误信息'密码6-20位字符'
        And jobs提示错误信息'员工姓名内容不能为空'
        And jobs提示错误信息'部门请选择一个选项'
    #8字符数的校验（账户名称4-20位字符、密码6-20位字符）
        When jobs新建员工
            """
            [{
                "employees":
                [{
                    "account_name":"账户名称大于20位字符",
                    "password":"密码大于20位字符",
                    "confirm_password":"密码大于20位字符",
                    "employee_name":"张06",
                    "department_name":"部门1"
                }]
                "roles":
                [{
                    "role_name":"角色0",
                    "is_selected":"N"
                },{
                    "role_name":"角色1",
                    "is_selected":"N"
                },{
                    "role_name":"角色2",
                    "is_selected":"N"
                }]
                "permissions":
                [{
                    "presentation":"此员工未设置权限",
                    "type":"",
                    "values":""
                }]
            }]
            """
        Then jobs提示错误信息'账户名称4-20位字符'
        And jobs提示错误信息'密码6-20位字符'
    #9修改和删除角色时，新建员工页面随之相应的改变
        #修改角色(角色0改为角色00，添加图片管理权限)
            Given jobs已修改角色'角色0'
                """
                [{
                    "role_name":"角色00",
                    #"button":"修改权限",
                    "permissions":
                    [{
                        "type":"商品管理"，
                        "value":
                            [{
                                "name":"图片管理"
                            }]
                    }]
                }]
                """
            When jobs新建员工
                """
                [{
                    "employees":
                    [{
                        "account_name":"ceshi05",
                        "password":"123456a",
                        "confirm_password":"123456a",
                        "employee_name":"张05",
                        "department_name":"部门1"
                    }]
                    "roles":
                    [{
                        "role_name":"角色00",
                        "is_selected":"Y"
                    },{
                        "role_name":"角色1",
                        "is_selected":"N"
                    },{
                        "role_name":"角色2",
                        "is_selected":"N"
                    }]
                    "permissions":
                    [{
                        "presentation":"",
                        "type":"商品管理",
                        "value":
                            [{
                                "name":"图片管理"
                            }]
                    }]
                }]
                """
            Then jobs获取员工信息列表
                """
                [{
                    "reminder":"",
                    "employees":
                    [{
                        "account_name":"ceshi05",
                        "employee_name":"张05",
                        "department_name":"部门1",
                        "roles":"角色00",
                        "is_active":"启用"
                    },{
                        "account_name":"ceshi04",
                        "employee_name":"张04",
                        "department_name":"部门1",
                        "roles":"角色00及其他",
                        "is_active":"启用"
                    },{
                        "account_name":"ceshi03",
                        "employee_name":"张03",
                        "department_name":"部门1",
                        "roles":"角色00及其他",
                        "is_active":"启用"
                    },{
                        "account_name":"ceshi02",
                        "employee_name":"张02",
                        "department_name":"部门1",
                        "roles":"角色1",
                        "is_active":"启用"
                    },{
                        "account_name":"ceshi01",
                        "employee_name":"张01",
                        "department_name":"部门1",
                        "roles":"角色00",
                        "is_active":"启用"
                    },{
                        "account_name":"ceshi00",
                        "employee_name":"张00",
                        "department_name":"部门1",
                        "roles":"",
                        "is_active":"启用"
                    }]
                }]
                """
        #删除角色，子账号对应的角色也相应被删除（删除角色1、角色2）
            Given jobs已删除角色 '角色1,角色2'
            When jobs新建员工
                """
                [{
                    "employees":
                    [{
                        "account_name":"ceshi06",
                        "password":"123456a",
                        "confirm_password":"123456a",
                        "employee_name":"张06",
                        "department_name":"部门1"
                    }]
                    "roles":
                    [{
                        "role_name":"角色00",
                        "is_selected":"N"
                    }]
                    "permissions":
                    [{
                        "presentation":"此员工未设置权限",
                        "type":"",
                        "values":""
                    }]
                }]
                """
            Then jobs获取员工信息列表
                """
                [{
                    "reminder":"",
                    "employees":
                    [{
                        "account_name":"ceshi06",
                        "employee_name":"张06",
                        "department_name":"部门1",
                        "roles":"",
                        "is_active":"启用"
                 },{
                    "account_name":"ceshi05",
                     "employee_name":"张05",
                     "department_name":"部门1",
                     "roles":"角色00",
                     "is_active":"启用"
                    },{
                        "account_name":"ceshi04",
                        "employee_name":"张04",
                        "department_name":"部门1",
                        "roles":"角色00",
                        "is_active":"启用"
                    },{
                        "account_name":"ceshi03",
                        "employee_name":"张03",
                        "department_name":"部门1",
                        "roles":"角色00",
                        "is_active":"启用" 
                    },{
                        "account_name":"ceshi02",
                        "employee_name":"张02",
                        "department_name":"部门1",
                        "roles":"",
                        "is_active":"启用"
                    },{
                        "account_name":"ceshi01",
                        "employee_name":"张01",
                        "department_name":"部门1",
                        "roles":"角色00",
                        "is_active":"启用"
                    },{
                        "account_name":"ceshi00",
                        "employee_name":"张00",
                        "department_name":"部门1",
                        "roles":"",
                        "is_active":"启用"
                    }]
                }]
                """
#10启用和停用子账号
#停用子账号（ceshi04）
    When jobs停用子账号'ceshi04'
    #Then jobs弹出信息提示'确认停用该员工'
    And jobs确认停用
    Then 子账号'ceshi04'已停用
        """
        [{
            "account_name":"ceshi04",
            "employee_name":"张04",
            "department_name":"部门1",
            "roles":"角色00",
            "is_active":"停用"
        }]
        """
    And 子账号 'ceshi04'无法登录系统
#启用子账号(ceshi03)
    When jobs停用子账号'ceshi03'
    #Then jobs弹出信息提示'确认停用该员工' 
    And jobs确认停用
    Then 子账号'ceshi03'已停用
        """
        [{
            "account_name":"ceshi03",
            "employee_name":"张03",
            "department_name":"部门1",
            "roles":"角色00",
            "is_active":"停用"
        }]
        """
    And 子账号 'ceshi03'无法登录系统
    When jobs启用子账号'ceshi03'
    Then 子账号'ceshi03'已启用
        """
        [{
            "account_name":"ceshi03",
            "employee_name":"张03",
            "department_name":"部门1",
            "roles":"角色00",
            "is_active":"启用"
        }]
        """
    And 子账号'ceshi03'可以登录系统

#11删除员工（ceshi04-停用状态）
    When jobs删除员工'ceshi04'
    #Then jobs弹出提示信息
    And jobs确认删除
    Then jobs获取员工信息列表
        """
        [{
            "reminder":"",
            "employees":
            [{
                "account_name":"ceshi06",
                "employee_name":"张06",
                "department_name":"部门1",
                "roles":"",
                "is_active":"启用"
            },{
                "account_name":"ceshi05",
                "employee_name":"张05",
                "department_name":"部门1",
                "roles":"角色00",
                "is_active":"启用"
            },{
                "account_name":"ceshi03",
                "employee_name":"张03",
                "department_name":"部门1",
                "roles":"角色00",
                "is_active":"启用"  
            },{
                "account_name":"ceshi02",
                "employee_name":"张02",
                "department_name":"部门1",
                "roles":"",
                "is_active":"启用"
            },{
                "account_name":"ceshi01",
                "employee_name":"张01",
                "department_name":"部门1",
                "roles":"角色00",
                "is_active":"启用"
            },{
                "account_name":"ceshi00",
                "employee_name":"张00",
                "department_name":"部门1",
                "roles":"",
                "is_active":"启用"
            }]
        }]
        """
    And 子账号'ceshi04'无法登录系统

#12子账号上限为50（所有部门的总和）
Scenario:2 所有部门子账号总和不能超过50
    Given jobs登录系统
    And jobs已添加角色信息
        """
        [{
            "role_name":"角色0",
            #"button":"添加权限",
            "permissions":
            [{
                "type":""，
                "value":
                [{
                    "name":"暂未给此角色添加权限"
                }]
            }]
        },{
            "role_name":"角色1",
            #"button":"修改权限",
            "permissions":
            [{
                "type":"商品管理"，
                "value":
                    [
                        {"name":"添加新商品"},
                        {"name":"在售商品管理"},
                        {"name":"待售商品管理"}
                    ]
            }]
        },{
            "role_name":"角色2",
            #"button":"修改权限",
            "permissions":
                [{
                    "type":"商品管理"，
                    "value":
                    [{
                        "name":"添加新商品"
                    }]
                },{
                    "type":"促销管理"，
                    "value":
                    [
                        {"name":"促销查询"},
                        {"name":"限时抢购"}
                    ]
                },{
                    "type":"配置管理"，
                    "value":
                    [
                        {"name":"运费模板"},
                        {"name":"物流名称管理"},
                        {"name":"支付方式"}
                    ]
                }]
        }]
        """
    And jobs已新建部门
        """
        [
            {"department_name":"部门a"},
            {"department_name":"部门b"},
            {"department_name":"部门c"}
        ]
        """
    #已经新建了50个账号，开发人员之间在数据库中插入50个账号信息
    And jobs已新建员工
        """
        [{
            "reminder":"",
            "employees":
            [{
                "account_name":"ceshi50",
                "employee_name":"张50",
                "department_name":"部门c",
                "roles":"角色0及其他",
                "is_active":"启用"
            },{
                "account_name":"ceshi01",
                "employee_name":"张01",
                "department_name":"部门a",
                "roles":"角色0及其他",
                "is_active":"启用"
            }]
        }]
        """
    #若达到50个子账号后再添加新的子账号时提示：“已达到子账号最大限额（50）”    
    When jobs新建员工
        """
        [{
            "employees":
            [{
                "account_name":"ceshi51",
                "password":"123456a",
                "confirm_password":"123456a",
                "employee_name":"张51",
                "department_name":"部门c"
            }]
            "roles":
            [{
                "role_name":"角色0",
                "is_selected":"N"
            },{
                "role_name":"角色1",
                "is_selected":"N"
            },{
                "role_name":"角色2",
                "is_selected":"N"
            }]
            "permissions":
            [{
                "presentation":"此员工未设置权限",
                "type":"",
                "values":""
            }]
        }]
        """
    Then jobs提示错误信息 '已达到子账号最大限额(50)'

