#_author_zhangsx

Feature:员工信息-对员工信息、部门、权限进行修改
 可以修改的内容：
   a.员工姓名
   b.部门
   c.角色
   d.补充权限：可为账号赋予超出已选角色范围以外的权限；补充权限时不可删减该	员工已经获得角色涵盖的权限；当角色和补充权限存在交集时，只添加一次相应的权限。
Background:
     Given jobs登录系统
     And jobs已添加角色信息
         """
         [{
             "role_name":"角色0",
            #"button":"添加权限",
             "permissions":
             [{
                  "type":""，
                   "value":
                   [{
                      "name":"暂未给此角色添加权限"
                   }]
             }]
          
         },{
             "role_name":"角色1",
             #"button":"修改权限",
             "permissions":
             [{
                 "type":"商品管理"，
                 "value":
                     [
                         {"name":"添加新商品"},
                         {"name":"在售商品管理"},
                         {"name":"待售商品管理"}
                     ]
             }]
         }]
         """
     And jobs已新建部门
         """
         [
             {"department_name":"部门1"},
             {"department_name":"部门2"}
         ]
         """
     When jobs新建员工
         """
         [{
             "employees":
              [{
                 "account_name":"ceshi01",
                 "password":"123456a",
                 "confirm_password":"123456a",
                 "employee_name":"张01",
                 "department_name":"部门1"
             }]
             "roles":
             [{
                 "role_name":"角色0",
                 "is_selected":"Y"
             },{
                 "role_name":"角色1",
                 "is_selected":"N"
             }]
             "permissions":
              [{
                 "presentation":"此员工未设置权限",
                 "type":"",
                 "values":""
               }]
         }]
         """
     Then jobs获取员工信息列表
         """
         [{ 
             "reminder":"",
             "employees":
              [{
                 "account_name":"ceshi01",
                 "employee_name":"张01",
                 "department_name":"部门1",

                 "roles":"角色0",
                 "is_active":"启用"
             }]
         }]
         """          
     When jobs新建员工
         """
         [{
             "employees":
              [{
                 "account_name":"ceshi02",
                 "password":"123456a",
                 "confirm_password":"123456a",
                 "employee_name":"张02",
                 "department_name":"部门1"
             }]
             "roles":
             [{
                 "role_name":"角色0",
                 "is_selected":"N"
             },{
                 "role_name":"角色1",
                 "is_selected":"Y"
             }]
             "permissions":
              [{
                 "presentation":"",
                 "type":"商品管理"，
                 "value":
                     [
                         {"name":"添加新商品"},
                         {"name":"在售商品管理"},
                         {"name":"待售商品管理"}
                     ]
               }]
         }]
         """   
     Then jobs获取员工信息列表
         """
         [{ 
             "reminder":"",
             "employees":
              [{
                "account_name":"ceshi02",
                 "employee_name":"张02",
                 "department_name":"部门1",
                 "roles":"角色1",
                 "is_active":"启用"
             },{
                 "account_name":"ceshi01",
                 "employee_name":"张01",
                 "department_name":"部门1",
                 "roles":"角色0",
                 "is_active":"启用"
             }]
         }]
         """          
Scenario:1 员工信息-对员工信息、部门、权限进行修改
 #修改员工信息-员工姓名和部门为空（ceshi02）
 When jobs修改员工信息'ceshi02'
     """
     [{
         #"button":"补充权限",
         "employees":
              [{
                 "account_name":"ceshi02",
                 "employee_name":"",
                 "department_name":""
             }]
         "roles":
             [{
                 "role_name":"角色0",
                 "is_selected":"N"
             },{
                 "role_name":"角色1",
                 "is_selected":"Y"
             }]
         "permissions":
             [{
                 "presentation":"",
                 "type":"商品管理"，
                 "value":
                     [
                         {"name":"添加新商品"},
                         {"name":"在售商品管理"},
                         {"name":"待售商品管理"}
                     ]
             }]
         }]
         """
 Then jobs提示错误信息'员工姓名不能为空'
 And jobs提示错误信息'部门请选择一个选项'

 #修改员工信息-员工姓名、部门、角色(ceshi01的"张01,部门1,角色0"修改为"张001,部门2,角色1")
 When jobs修改员工信息'ceshi01'
     """
     [{
         #"button":"补充权限",
         "employees":
              [{
                 "account_name":"ceshi01",
                 "employee_name":"张001",
                 "department_name":"部门2"
             }]
         "roles":
             [{
                 "role_name":"角色0",
                 "is_selected":"N"
             },{
                 "role_name":"角色1",
                 "is_selected":"Y"
             }]
         "permissions":
             [{
                 "presentation":"",
                 "type":"商品管理"，
                 "value":
                     [
                         {"name":"添加新商品"},
                         {"name":"在售商品管理"},
                         {"name":"待售商品管理"}
                     ]
             }]
         }]
         """
 Then jobs获取员工信息列表
         """
         [{ 
             "reminder":"",
             "employees":
              [{
                 "account_name":"ceshi02",
                 "employee_name":"张02",
                 "department_name":"部门1",
                 "roles":"角色1",
                 "is_active":"启用"
              },{
                 "account_name":"ceshi01",
                 "employee_name":"张001",
                 "department_name":"部门2",
                 "roles":"角色1",
                 "is_active":"启用"
         }]
         """          
 
 #补充权限(ceshi01)
 #补充权限时不可删减该员工已经获得角色涵盖的权限
 When jobs查看补充权限
 Then jobs获取用户已设置的权限信息
     """
     [{
         "setting_user_permission":
             [{
                 "type":"商品管理",
                 "value":
                     [{
                         "name":"添加新商品",
                         "check_box":
                             [{
                                 "is_select":"Y",
                                 "is_active":"N"
                             }]
                         
                     },{
                         "name":"在售商品管理",
                         "check_box":
                             [{
                                 "is_select":"Y",
                                 "is_active":"N"
                             }]
                     },{
                         "name":"待售商品管理",
                         "check_box":
                             [{
                                 "is_select":"Y",
                                 "is_active":"N"
                             }]
                     },{
                         "name":"商品回收站",
                         "check_box":
                             [{
                                 "is_select":"N",
                                 "is_active":"Y"
                             }]
                     },{
                         "name":"图片管理",
                         "check_box":
                             [{
                                 "is_select":"N",
                                 "is_active":"Y"
                             }]
                     },{
                         "name":"分组管理",
                         "check_box":
                             [{
                                 "is_select":"N",
                                 "is_active":"Y"
                             }]
                     },{
                         "name":"属性管理",
                         "check_box":
                             [{
                                 "is_select":"N",
                                 "is_active":"Y"
                             }]
                     }]
             },{
                 "type":"促销管理",
                 "value":
                     [{
                         "name":"促销查询",
                         "check_box":
                             [{
                                 "is_select":"N",
                                 "is_active":"Y"
                             }]
                     },{
                         "name":"限时抢购",
                         "check_box":
                             [{
                                 "is_select":"N",
                                 "is_active":"Y"
                             }]
                     },{  
                         "name":"买赠",
                         "check_box":
                             [{
                                 "is_select":"N",
                                 "is_active":"Y"
                             }]
                     },{
                         "name":"满减",
                         "check_box":
                             [{
                                 "is_select":"N",
                                 "is_active":"Y"
                             }]
                     },{
                         "name":"优惠券",
                         "check_box":
                             [{
                                 "is_select":"N",
                                 "is_active":"Y"
                             }]
                     },{
                         "name":"积分应用",
                         "check_box":
                             [{
                                 "is_select":"N",
                                 "is_active":"Y"
                             }]
                     }]
             },{
                 "type":"配置管理",
                 "value":
                     [{
                         "name":"运费模板",
                        "check_box":
                             [{
                                 "is_select":"N",
                                 "is_active":"Y"
                             }]
                     },{
                         "name":"物流名称管理",
                         "check_box":
                             [{
                                 "is_select":"N",
                                 "is_active":"Y"
                             }]
                     },{
                         "name":"支付方式",
                         "check_box":
                             [{
                                 "is_select":"N",
                                 "is_active":"Y"
                             }]
                     }]
             },{
                 "type":"权限管理",
                 "value":
                     [{
                         "name":"账号帮助",
                         "check_box":
                             [{
                                 "is_select":"N",
                                 "is_active":"Y"
                             }]
                     },{
                         "name":"角色管理",
                         "check_box":
                             [{
                                 "is_select":"N",
                                 "is_active":"Y"
                             }]
                     },{
                         "name":"员工管理",
                         "check_box":
                             [{
                                 "is_select":"N",
                                 "is_active":"Y"
                             }]
                     }]
             }]
     }]
     """
 When jobs补充权限
     """
     [{
         "setting_user_permission":
             [{
                 "type":"商品管理",
                 "value":
                     [{
                         "name":"添加新商品",
                         "check_box":
                             [{
                                 "is_select":"Y",
                                 "is_active":"N"
                             }]
                         
                     },{
                         "name":"在售商品管理",
                         "check_box":
                             [{
                                 "is_select":"Y",
                                 "is_active":"N"
                             }]
                     },{
                         "name":"待售商品管理",
                         "check_box":
                             [{
                                 "is_select":"Y",
                                 "is_active":"N"
                             }]
                     },{
                         "name":"商品回收站",
                         "check_box":
                             [{
                                 "is_select":"N",
                                 "is_active":"Y"
                             }]
                     },{
                         "name":"图片管理",
                         "check_box":
                             [{
                                 "is_select":"N",
                                 "is_active":"Y"
                             }]
                     },{
                         "name":"分组管理",
                         "check_box":
                             [{
                                 "is_select":"N",
                                 "is_active":"Y"
                             }]
                     },{
                         "name":"属性管理",
                         "check_box":
                             [{
                                 "is_select":"N",
                                 "is_active":"Y"
                             }]
                     }]
             },{
                 "type":"促销管理",
                 "value":
                     [{
                         "name":"促销查询",
                         "check_box":
                             [{
                                 "is_select":"Y",
                                 "is_active":"Y"
                             }]
                     },{
                         "name":"限时抢购",
                         "check_box":
                             [{
                                 "is_select":"Y",
                                 "is_active":"Y"
                             }]
                     },{  
                         "name":"买赠",
                         "check_box":
                             [{
                                 "is_select":"Y",
                                 "is_active":"Y"
                             }]
                     },{
                         "name":"满减",
                         "check_box":
                             [{
                                 "is_select":"N",
                                 "is_active":"Y"
                             }]
                     },{
                         "name":"优惠券",
                         "check_box":
                             [{
                                 "is_select":"N",
                                 "is_active":"Y"
                             }]
                     },{
                         "name":"积分应用",
                         "check_box":
                             [{
                                 "is_select":"N",
                                 "is_active":"Y"
                             }]
                     }]
             },{
                 "type":"配置管理",
                 "value":
                     [{
                         "name":"运费模板",
                        "check_box":
                             [{
                                 "is_select":"N",
                                 "is_active":"Y"
                             }]
                     },{
                         "name":"物流名称管理",
                         "check_box":
                             [{
                                 "is_select":"N",
                                 "is_active":"Y"
                             }]
                     },{
                         "name":"支付方式",
                         "check_box":
                             [{
                                 "is_select":"N",
                                 "is_active":"Y"
                             }]
                     }]
             },{
                 "type":"权限管理",
                 "value":
                     [{
                         "name":"账号帮助",
                         "check_box":
                             [{
                                 "is_select":"N",
                                 "is_active":"Y"
                             }]
                     },{
                         "name":"角色管理",
                         "check_box":
                             [{
                                 "is_select":"N",
                                 "is_active":"Y"
                             }]
                     },{
                         "name":"员工管理",
                         "check_box":
                             [{
                                 "is_select":"N",
                                 "is_active":"Y"
                             }]
                     }]
             }]
     }]
     """ 
 Then jobs获取员工信息
     """
     [{
         #"button":"补充权限",
         "employees":
              [{
                 "account_name":"ceshi01",
                 "employee_name":"张001",
                 "department_name":"部门2"
             }]
         "roles":
             [{
                 "role_name":"角色0",
                 "is_selected":"N"
             },{
                 "role_name":"角色1",
                 "is_selected":"Y"
             }]
         "permissions":
             [{
                 "presentation":"",
                 [{
                     "type":"商品管理"，
                     "value":
                     [
                         {"name":"添加新商品"},
                         {"name":"在售商品管理"},
                         {"name":"待售商品管理"}
                     ]
                 },{
                     "type":"促销管理",
                     "value":
                     [
                         {"name":"促销查询"},
                         {"name":"限时抢购"},
                         {"name":"买赠"}
                     ]
                 }]
             }]   
         }]
         """
 When jobs修改补充权限
     """
     [{
         "setting_user_permission":
             [{
                 "type":"商品管理",
                 "value":
                     [{
                         "name":"添加新商品",
                         "check_box":
                             [{
                                 "is_select":"Y",
                                 "is_active":"N"
                             }]
                         
                     },{
                         "name":"在售商品管理",
                         "check_box":
                             [{
                                 "is_select":"Y",
                                 "is_active":"N"
                             }]
                     },{
                         "name":"待售商品管理",
                         "check_box":
                             [{
                                 "is_select":"Y",
                                 "is_active":"N"
                             }]
                     },{
                         "name":"商品回收站",
                         "check_box":
                             [{
                                 "is_select":"N",
                                 "is_active":"Y"
                             }]
                     },{
                         "name":"图片管理",
                         "check_box":
                             [{
                                 "is_select":"N",
                                 "is_active":"Y"
                             }]
                     },{
                         "name":"分组管理",
                         "check_box":
                             [{
                                 "is_select":"N",
                                 "is_active":"Y"
                             }]
                     },{
                         "name":"属性管理",
                         "check_box":
                             [{
                                 "is_select":"N",
                                 "is_active":"Y"
                             }]
                     }]
             },{
                 "type":"促销管理",
                 "value":
                     [{
                         "name":"促销查询",
                         "check_box":
                             [{
                                 "is_select":"Y",
                                 "is_active":"Y"
                             }]
                     },{
                         "name":"限时抢购",
                         "check_box":
                             [{
                                 "is_select":"Y",
                                 "is_active":"Y"
                             }]
                     },{  
                         "name":"买赠",
                         "check_box":
                             [{
                                 "is_select":"N",
                                 "is_active":"Y"
                             }]
                     },{
                         "name":"满减",
                         "check_box":
                             [{
                                 "is_select":"N",
                                 "is_active":"Y"
                             }]
                     },{
                         "name":"优惠券",
                         "check_box":
                             [{
                                 "is_select":"N",
                                 "is_active":"Y"
                             }]
                     },{
                         "name":"积分应用",
                         "check_box":
                             [{
                                 "is_select":"N",
                                 "is_active":"Y"
                             }]
                     }]
             },{
                 "type":"配置管理",
                 "value":
                     [{
                         "name":"运费模板",
                        "check_box":
                             [{
                                 "is_select":"N",
                                 "is_active":"Y"
                             }]
                     },{
                         "name":"物流名称管理",
                         "check_box":
                             [{
                                 "is_select":"N",
                                 "is_active":"Y"
                             }]
                     },{
                         "name":"支付方式",
                         "check_box":
                             [{
                                 "is_select":"N",
                                 "is_active":"Y"
                             }]
                     }]
             },{
                 "type":"权限管理",
                 "value":
                     [{
                         "name":"账号帮助",
                         "check_box":
                             [{
                                 "is_select":"N",
                                 "is_active":"Y"
                             }]
                     },{
                         "name":"角色管理",
                         "check_box":
                             [{
                                 "is_select":"N",
                                 "is_active":"Y"
                             }]
                     },{
                         "name":"员工管理",
                         "check_box":
                             [{
                                 "is_select":"N",
                                 "is_active":"Y"
                             }]
                     }]
             }]
     }]
     """        
 Then jobs获取员工信息
     """
     [{
         #"button":"补充权限",
         "employees":
              [{
                 "account_name":"ceshi01",
                 "employee_name":"张001",
                 "department_name":"部门2"
             }]
         "roles":
             [{
                 "role_name":"角色0",
                 "is_selected":"N"
             },{
                 "role_name":"角色1",
                 "is_selected":"Y"
             }]
         "permissions":
             [{
                 "presentation":"",
                 [{
                     "type":"商品管理"，
                     "value":
                     [
                         {"name":"添加新商品"},
                         {"name":"在售商品管理"},
                         {"name":"待售商品管理"}
                     ]
                 },{
                     "type":"促销管理",
                     "value":
                     [
                         {"name":"促销查询"},
                         {"name":"限时抢购"}
                     ]
                 }]
             }]   
         }]
         """
 




