#_author_:zhangsx

Feature:角色管理-添加权限、修改权限

Background:
    Given jobs登录系统
    And jobs已添加角色权限信息
        """
        [{
            "setting_role_permission":
                [{
                    "type":"商品管理",
                    "value":
                        [{
                            "name":"添加新商品",
                            "check_box":
                                [{
                                    "is_select":"N",
                                    "is_active":"Y"
                                }]
                        },{
                            "name":"在售商品管理",
                            "check_box":
                                [{
                                    "is_select":"N",
                                    "is_active":"Y"
                                }]
                        },{
                            "name":"待售商品管理",
                            "check_box":
                                [{
                                    "is_select":"N",
                                    "is_active":"Y"
                                }]
                        },{
                            "name":"商品回收站",
                            "check_box":
                                [{
                                    "is_select":"N",
                                    "is_active":"Y"
                                }]
                        },{
                            "name":"图片管理",
                            "check_box":
                                [{
                                    "is_select":"N",
                                    "is_active":"Y"
                                }]
                        },{
                            "name":"分组管理",
                            "check_box":
                                [{
                                    "is_select":"N",
                                    "is_active":"Y"
                                }]
                        },{
                            "name":"属性管理",
                            "check_box":
                                [{
                                    "is_select":"N",
                                    "is_active":"Y"
                                }]
                        }]
                },{
                    "type":"促销管理",
                    "value":
                        [{
                            "name":"促销查询",
                            "check_box":
                                [{
                                    "is_select":"N",
                                    "is_active":"Y"
                                }]
                        },{
                            "name":"限时抢购",
                            "check_box":
                                [{
                                    "is_select":"N",
                                    "is_active":"Y"
                                }]
                        },{
                            "name":"买赠",
                            "check_box":
                                [{
                                    "is_select":"N",
                                    "is_active":"Y"
                                }]
                        },{
                            "name":"满减",
                            "check_box":
                                [{
                                    "is_select":"N",
                                    "is_active":"Y"
                                }]
                        },{
                            "name":"优惠券",
                            "check_box":
                                [{
                                    "is_select":"N",
                                    "is_active":"Y"
                                }]
                        },{
                            "name":"积分应用",
                            "check_box":
                                [{
                                    "is_select":"N",
                                    "is_active":"Y"
                                }]
                        }]
                },{
                    "type":"配置管理",
                    "value":
                        [{
                            "name":"运费模板",
                            "check_box":
                                [{
                                    "is_select":"N",
                                    "is_active":"Y"
                                }]
                        },{
                            "name":"物流名称管理",
                            "check_box":
                                [{
                                    "is_select":"N",
                                    "is_active":"Y"
                                }]
                        },{
                            "name":"支付方式",
                            "check_box":
                                [{
                                    "is_select":"N",
                                    "is_active":"Y"
                                }]
                        }]
                },{
                    "type":"权限管理",
                    "value":
                        [{
                            "name":"账号帮助",
                            "check_box":
                                [{
                                    "is_select":"N",
                                    "is_active":"Y"
                                }]
                        },{
                            "name":"角色管理",
                            "check_box":
                                [{
                                    "is_select":"N",
                                    "is_active":"Y"
                                }]
                        },{
                            "name":"员工管理",
                            "check_box":
                                [{
                                    "is_select":"N",
                                    "is_active":"Y"
                                }]
                        }]
                }]
        }]
        """
    And jobs已添加角色信息
        """
        [{
            "role_name":"角色3",
            #"button":"添加权限",
            "permissions":
                [{
                    "type":""，
                    "value":
                    [{
                        "name":"暂未给此角色添加权限"
                    }]
                }]
        },{
            "role_name":"角色2",
            #"button":"添加权限",
            "permissions":
                [{
                    "type":""，
                    "value":
                    [{
                        "name":"暂未给此角色添加权限"
                    }]
                }]
        },{
            "role_name":"角色1",
            #"button":"添加权限",
            "permissions":
                [{
                    "type":""，
                    "value":
                    [{
                        "name":"暂未给此角色添加权限"
                    }]
                }]
        }]
        """
#添加权限
Scenario:1 添加一种权限类别（角色1，商品管理）
    When jobs添加权限
        """
        [{
            "setting_role_permission":
                [{
                    "type":"商品管理",
                    "value":
                        [{
                            "name":"添加新商品",
                            "check_box":
                                [{
                                    "is_select":"Y",
                                    "is_active":"Y"
                                }]
                        },{
                            "name":"在售商品管理",
                            "check_box":
                                [{
                                    "is_select":"Y",
                                    "is_active":"Y"
                                }]
                        },{
                            "name":"待售商品管理",
                            "check_box":
                                [{
                                    "is_select":"Y",
                                    "is_active":"Y"
                                }]
                        },{
                            "name":"商品回收站",
                            "check_box":
                                [{
                                    "is_select":"N",
                                    "is_active":"Y"
                                }]
                        },{
                            "name":"图片管理",
                            "check_box":
                                [{
                                    "is_select":"N",
                                    "is_active":"Y"
                                }]
                        },{
                            "name":"分组管理",
                            "check_box":
                                [{
                                    "is_select":"N",
                                    "is_active":"Y"
                                }]
                        },{
                            "name":"属性管理",
                            "check_box":
                                [{
                                    "is_select":"N",
                                    "is_active":"Y"
                                }]
                        }]
                },{
                    "type":"促销管理",
                    "value":
                        [{
                            "name":"促销查询",
                            "check_box":
                                [{
                                    "is_select":"N",
                                    "is_active":"Y"
                                }]
                        },{
                            "name":"限时抢购",
                            "check_box":
                                [{
                                    "is_select":"N",
                                    "is_active":"Y"
                                }]
                        },{
                            "name":"买赠",
                            "check_box":
                                [{
                                    "is_select":"N",
                                    "is_active":"Y"
                                }]
                        },{
                            "name":"满减",
                            "check_box":
                                [{
                                    "is_select":"N",
                                    "is_active":"Y"
                                }]
                        },{
                            "name":"优惠券",
                            "check_box":
                                [{
                                    "is_select":"N",
                                    "is_active":"Y"
                                }]
                        },{
                            "name":"积分应用",
                            "check_box":
                                [{
                                    "is_select":"N",
                                    "is_active":"Y"
                                }]
                        }]
                },{
                    "type":"配置管理",
                    "value":
                        [{
                            "name":"运费模板",
                            "check_box":
                                [{
                                    "is_select":"N",
                                    "is_active":"Y"
                                }]
                        },{
                            "name":"物流名称管理",
                            "check_box":
                                [{
                                    "is_select":"N",
                                    "is_active":"Y"
                                }]
                        },{
                            "name":"支付方式",
                            "check_box":
                                [{
                                    "is_select":"N",
                                    "is_active":"Y"
                                }]
                        }]
                },{
                    "type":"权限管理",
                    "value":
                        [{
                            "name":"账号帮助",
                            "check_box":
                                [{
                                    "is_select":"N",
                                    "is_active":"Y"
                                }]
                        },{
                            "name":"角色管理",
                            "check_box":
                                [{
                                    "is_select":"N",
                                    "is_active":"Y"
                                }]
                        },{
                            "name":"员工管理",
                            "check_box":
                                [{
                                    "is_select":"N",
                                    "is_active":"Y"
                                }]
                        }]
                }]
        }]
        """
    Then jobs获取角色信息
        """
        [{
            "role_name":"角色1",
            #"button":"修改权限",
            "permissions":
            [{
                "type":"商品管理"，
                "value":
                [{
                    "name":"添加新商品",
                    "name":"在售商品管理",
                    "name":"待售商品管理"
                }]
            }]
        }]
        """

Scenario:2 添加多种权限类别（角色2，商品管理、促销管理、配置管理）
    When jobs添加权限
        """
        [{
            "setting_role_permission":
                [{
                    "type":"商品管理",
                    "value":
                        [{
                            "name":"添加新商品",
                            "check_box":
                                [{
                                    "is_select":"Y",
                                    "is_active":"Y"
                                }]
                        },{
                            "name":"在售商品管理",
                            "check_box":
                                [{
                                    "is_select":"N",
                                    "is_active":"Y"
                                }]
                        },{
                            "name":"待售商品管理",
                            "check_box":
                                [{
                                    "is_select":"N",
                                    "is_active":"Y"
                                }]
                        },{
                            "name":"商品回收站",
                            "check_box":
                                [{
                                    "is_select":"N",
                                    "is_active":"Y"
                                }]
                        },{
                            "name":"图片管理",
                            "check_box":
                                [{
                                    "is_select":"N",
                                    "is_active":"Y"
                                }]
                        },{
                            "name":"分组管理",
                            "check_box":
                                [{
                                    "is_select":"N",
                                    "is_active":"Y"
                                }]
                        },{
                            "name":"属性管理",
                            "check_box":
                                [{
                                    "is_select":"N",
                                    "is_active":"Y"
                                }]
                        }]
                },{
                    "type":"促销管理",
                    "value":
                        [{
                            "name":"促销查询",
                            "check_box":
                                [{
                                    "is_select":"Y",
                                    "is_active":"Y"
                                }]
                        },{
                            "name":"限时抢购",
                            "check_box":
                                [{
                                    "is_select":"Y",
                                    "is_active":"Y"
                                }]
                     },{
                         "name":"买赠",
                         "check_box":
                             [{
                                 "is_select":"N",
                                 "is_active":"Y"
                             }]
                        },{
                            "name":"满减",
                            "check_box":
                                [{
                                    "is_select":"N",
                                    "is_active":"Y"
                                }]
                        },{
                            "name":"优惠券",
                            "check_box":
                                [{
                                    "is_select":"N",
                                    "is_active":"Y"
                                }]
                        },{
                            "name":"积分应用",
                            "check_box":
                                [{
                                    "is_select":"N",
                                    "is_active":"Y"
                                }]
                        }]
                },{
                    "type":"配置管理",
                    "value":
                        [{
                            "name":"运费模板",
                            "check_box":
                                [{
                                    "is_select":"Y",
                                "is_active":"Y"
                                }]
                        },{
                            "name":"物流名称管理",
                            "check_box":
                                [{
                                    "is_select":"Y",
                                    "is_active":"Y"
                                }]
                        },{
                            "name":"支付方式",
                            "check_box":
                                [{
                                    "is_select":"Y",
                                    "is_active":"Y"
                                }]
                        }]
                },{
                    "type":"权限管理",
                    "value":
                        [{
                            "name":"账号帮助",
                            "check_box":
                                [{
                                    "is_select":"N",
                                    "is_active":"Y"
                                }]
                        },{
                            "name":"角色管理",
                            "check_box":
                                [{
                                    "is_select":"N",
                                    "is_active":"Y"
                                }]
                        },{
                            "name":"员工管理",
                            "check_box":
                                [{
                                    "is_select":"N",
                                    "is_active":"Y"
                                }]
                        }]
                }]
        }]
        """
    Then jobs获取角色信息
        """
        [{
            "role_name":"角色2",
            #"button":"修改权限",
            "permissions":
                [{
                    "type":"商品管理"，
                    "value":
                    [{
                        "name":"添加新商品"
                    }]
                },{
                    "type":"促销管理"，
                    "value":
                    [{
                        "name":"促销查询",
                        "name":"限时抢购"
                    }]
                },{
                    "type":"配置管理"，
                    "value":
                    [{
                        "name":"运费模板",
                        "name":"物流名称管理",
                        "name":"支付方式"
                    }]
                }]
          
        }]
        """

Scenario:3 添加所有权限类别（角色3，商品管理、促销管理、配置管理、权限管理）
    When jobs添加权限
        """
        [{
            "setting_role_permission":
            [{
                "type":"商品管理",
                "value":
                    [{
                        "name":"添加新商品",
                        "check_box":
                            [{
                                "is_select":"Y",
                                "is_active":"Y"
                            }]
                    },{
                        "name":"在售商品管理",
                        "check_box":
                            [{
                                "is_select":"Y",
                                "is_active":"Y"
                            }]
                    },{
                        "name":"待售商品管理",
                        "check_box":
                            [{
                                "is_select":"Y",
                                "is_active":"Y"
                            }]
                    },{
                        "name":"商品回收站",
                        "check_box":
                            [{
                                "is_select":"Y",
                                "is_active":"Y"
                            }]
                    },{
                        "name":"图片管理",
                        "check_box":
                            [{
                                "is_select":"Y",
                                "is_active":"Y"
                            }]
                    },{
                        "name":"分组管理",
                        "check_box":
                            [{
                                "is_select":"Y",
                                "is_active":"Y"
                            }]
                    },{
                        "name":"属性规格管理",
                        "check_box":
                            [{
                                "is_select":"Y",
                                "is_active":"Y"
                            }]
                    }]
            },{
                "type":"促销管理",
                "value":
                    [{
                        "name":"促销查询",
                        "check_box":
                            [{
                                "is_select":"Y",
                                "is_active":"Y"
                            }]
                    },{
                        "name":"限时抢购",
                        "check_box":
                            [{
                                "is_select":"Y",
                                "is_active":"Y"
                            }]
                    },{
                        "name":"买赠",
                        "check_box":
                            [{
                                "is_select":"Y",
                                "is_active":"Y"
                            }]
                    },{
                        "name":"满减",
                        "check_box":
                            [{
                                "is_select":"Y",
                                "is_active":"Y"
                            }]
                    },{
                        "name":"优惠券",
                        "check_box":
                            [{
                                "is_select":"Y",
                                "is_active":"Y"
                            }]
                    },{
                        "name":"积分应用",
                        "check_box":
                            [{
                                "is_select":"Y",
                                "is_active":"Y"
                            }]
                    }]
            },{
                "type":"配置管理",
                "value":
                    [{
                        "name":"运费模板",
                        "check_box":
                            [{
                                "is_select":"Y",
                                "is_active":"Y"
                            }]
                    },{
                        "name":"物流名称管理",
                        "check_box":
                            [{
                                "is_select":"Y",
                                "is_active":"Y"
                            }]
                    },{
                        "name":"支付方式",
                        "check_box":
                            [{
                                "is_select":"Y",
                                "is_active":"Y"
                            }]
                    }]
            },{
                "type":"权限管理",
                "value":
                    [{
                        "name":"账号帮助",
                        "check_box":
                            [{
                                "is_select":"Y",
                                "is_active":"Y"
                            }]
                    },{
                        "name":"角色管理",
                        "check_box":
                            [{
                                "is_select":"Y",
                                "is_active":"Y"
                            }]
                    },{
                        "name":"员工管理",
                        "check_box":
                            [{
                                "is_select":"Y",
                                "is_active":"Y"
                            }]
                    }]
            }]
        }]
        """
    Then jobs获取角色信息
        """
        [{
            "role_name":"角色3",
            #"button":"修改权限",
            "permissions":
                {
                    "type":"商品管理"，
                    "values":
                    [{
                        "name":"添加新商品",
                        "name":"在售商品管理",
                        "name":"待售商品管理",
                        "name":"商品回收站",
                        "name":"图片管理",
                        "name":"分组管理",
                        "name":"属性规格管理"
                    }]
                },{
                    "type":"促销管理"，
                    "values":
                     [{
                        "name":"促销查询",
                        "name":"限时抢购",
                        "name":"买赠",
                        "name":"满减",
                        "name":"优惠券",
                        "name":"积分应用"
                    }]
                },{
                    "type":"配置管理"，
                    "values":
                    [{
                        "name":"运费模板",
                        "name":"物流名称管理",
                        "name":"支付方式"
                    }]
                },{
                    "type":"权限管理"，
                    "values":
                    [{
                        "name":"账号帮助",
                        "name":"角色管理",
                        "name":"员工管理"
                    }]
                }
        }]
        """

#修改权限
Scenario:4 修改权限
    Given jobs已添加角色信息
        """
            [{
                "role_name":"角色4",
                #"button":"修改权限",
                "permissions":
                    [{
                        "type":"商品管理"，
                        "value":
                        [{
                            "name":"添加新商品",
                            "name":"在售商品管理",
                            "name":"待售商品管理"
                        }]
                    }]
            }]
        """
    #修改权限-添加权限（同类权限里面增加、添加另一类权限）
        When jobs修改权限
            """
            [{
            "setting_role_permission":
                [{
                    "type":"商品管理",
                    "value":
                    [{
                        "name":"添加新商品",
                        "check_box":
                            [{
                                "is_select":"Y",
                                "is_active":"Y"
                            }]
                    },{
                        "name":"在售商品管理",
                        "check_box":
                            [{
                                "is_select":"Y",
                                "is_active":"Y"
                            }]
                    },{
                        "name":"待售商品管理",
                        "check_box":
                            [{
                                "is_select":"Y",
                                "is_active":"Y"
                            }]
                    },{
                        "name":"商品回收站",
                        "check_box":
                            [{
                                "is_select":"N",
                                "is_active":"Y"
                            }]
                    },{
                        "name":"图片管理",
                        "check_box":
                            [{
                                "is_select":"Y",
                                "is_active":"Y"
                            }]
                    },{
                        "name":"分组管理",
                        "check_box":
                            [{
                                "is_select":"N",
                                "is_active":"Y"
                            }]
                    },{
                        "name":"属性管理",
                        "check_box":
                            [{
                                "is_select":"N",
                                "is_active":"Y"
                            }]
                    }]
                },{
                    "type":"促销管理",
                    "value":
                    [{
                        "name":"促销查询",
                        "check_box":
                            [{
                                "is_select":"Y",
                                "is_active":"Y"
                            }]
                    },{
                        "name":"限时抢购",
                        "check_box":
                            [{
                                "is_select":"N",
                                "is_active":"Y"
                            }]
                    },{
                        "name":"买赠",
                        "check_box":
                            [{
                                "is_select":"Y",
                                "is_active":"Y"
                            }]
                    },{
                        "name":"满减",
                        "check_box":
                            [{
                                "is_select":"N",
                                "is_active":"Y"
                            }]
                    },{
                        "name":"优惠券",
                        "check_box":
                            [{
                                "is_select":"N",
                                "is_active":"Y"
                            }]
                    },{
                        "name":"积分应用",
                        "check_box":
                            [{
                                "is_select":"N",
                                "is_active":"Y"
                            }]
                    }]
                },{
                    "type":"配置管理",
                    "value":
                    [{
                        "name":"运费模板",
                        "check_box":
                            [{
                                "is_select":"N",
                                "is_active":"Y"
                            }]
                    },{
                        "name":"物流名称管理",
                        "check_box":
                            [{
                                "is_select":"N",
                                "is_active":"Y"
                            }]
                    },{
                        "name":"支付方式",
                        "check_box":
                            [{
                                "is_select":"N",
                                "is_active":"Y"
                            }]
                    }]
                },{
                    "type":"权限管理",
                    "value":
                    [{
                        "name":"账号帮助",
                        "check_box":
                            [{
                                "is_select":"N",
                                "is_active":"Y"
                            }]
                    },{
                        "name":"角色管理",
                        "check_box":
                            [{
                                "is_select":"N",
                                "is_active":"Y"
                            }]
                    },{
                        "name":"员工管理",
                        "check_box":
                            [{
                                "is_select":"N",
                                "is_active":"Y"
                            }]
                    }]
                }]
            }]
            """
        Then jobs获取角色信息
            """
            [{
                "role_name":"角色4",
                #"button":"修改权限",
                "permissions":
                    {
                        "type":"商品管理",
                        "value":
                            [{
                                "name":"添加新商品",
                                "name":"在售商品管理",
                                "name":"待售商品管理",
                                "name":"图片管理"
                             }]
                    },{
                        "type":"促销管理"，
                        "value":
                            [{
                                "name":"促销查询",
                                "name":"买赠"
                            }]
                    }
            }]
            """

    #修改权限-删除权限
        When jobs修改权限
            """
            [{
                "setting_role_permission":
                [{
                    "type":"商品管理",
                    "value":
                    [{
                        "name":"添加新商品",
                        "check_box":
                            [{
                                "is_select":"Y",
                                "is_active":"Y"
                            }]
                    },{
                        "name":"在售商品管理",
                        "check_box":
                            [{
                                "is_select":"N",
                                "is_active":"Y"
                            }]
                    },{
                        "name":"待售商品管理",
                        "check_box":
                            [{
                                "is_select":"N",
                                "is_active":"Y"
                            }]
                    },{
                        "name":"商品回收站",
                        "check_box":
                            [{
                                "is_select":"N",
                                "is_active":"Y"
                            }]
                    },{
                        "name":"图片管理",
                        "check_box":
                            [{
                                "is_select":"Y",
                                "is_active":"Y"
                            }]
                    },{
                        "name":"分组管理",
                        "check_box":
                            [{
                                "is_select":"N",
                                "is_active":"Y"
                            }]
                    },{
                        "name":"属性管理",
                        "check_box":
                            [{
                                "is_select":"N",
                                "is_active":"Y"
                            }]
                    }]
                },{
                    "type":"促销管理",
                    "value":
                    [{
                        "name":"促销查询",
                        "check_box":
                            [{
                                "is_select":"N",
                                "is_active":"Y"
                            }]
                    },{
                        "name":"限时抢购",
                        "check_box":
                            [{
                                "is_select":"N",
                                "is_active":"Y"
                            }]
                    },{
                        "name":"买赠",
                        "check_box":
                            [{
                                "is_select":"Y",
                                "is_active":"Y"
                            }]
                    },{
                        "name":"满减",
                        "check_box":
                            [{
                                "is_select":"N",
                                "is_active":"Y"
                            }]
                    },{
                        "name":"优惠券",
                        "check_box":
                            [{
                                "is_select":"N",
                                "is_active":"Y"
                            }]
                    },{
                        "name":"积分应用",
                        "check_box":
                            [{
                                "is_select":"N",
                                "is_active":"Y"
                            }]
                    }]
                },{
                    "type":"配置管理",
                    "value":
                    [{
                        "name":"运费模板",
                        "check_box":
                            [{
                                "is_select":"N",
                                "is_active":"Y"
                            }]
                    },{
                        "name":"物流名称管理",
                        "check_box":
                            [{
                                "is_select":"N",
                                "is_active":"Y"
                            }]
                    },{
                        "name":"支付方式",
                        "check_box":
                            [{
                                "is_select":"N",
                                "is_active":"Y"
                            }]
                    }]
                },{
                    "type":"权限管理",
                    "value":
                    [{
                        "name":"账号帮助",
                        "check_box":
                            [{
                                "is_select":"N",
                                "is_active":"Y"
                            }]
                    },{
                        "name":"角色管理",
                        "check_box":
                            [{
                                "is_select":"N",
                                "is_active":"Y"
                            }]
                    },{
                        "name":"员工管理",
                        "check_box":
                            [{
                                "is_select":"N",
                                "is_active":"Y"
                            }]
                    }]
                }]
            }]
            """
        Then jobs获取角色信息
            """
            [{
                "role_name":"角色4",
                #"button":"修改权限",
                "permissions":
                    {
                        "type":"商品管理"，
                        "value":
                            [{
                                "name":"添加新商品",
                                "name":"图片管理"
                            }]
                    },{
                        "type":"促销管理"，
                        "value":
                            [{
                                "name":"买赠"
                            }]
                    }
            }]
            """

    #修改权限-删除所有权限
        When jobs修改权限
            """
            [{
                "setting_role_permission":
                [{
                    "type":"商品管理",
                    "value":
                    [{
                        "name":"添加新商品",
                        "check_box":
                            [{
                                "is_select":"N",
                                "is_active":"Y"
                            }]
                    },{
                        "name":"在售商品管理",
                        "check_box":
                            [{
                                "is_select":"N",
                                "is_active":"Y"
                            }]
                    },{
                        "name":"待售商品管理",
                        "check_box":
                            [{
                                "is_select":"N",
                                "is_active":"Y"
                            }]
                    },{
                        "name":"商品回收站",
                        "check_box":
                            [{
                                "is_select":"N",
                                "is_active":"Y"
                            }]
                    },{
                        "name":"图片管理",
                        "check_box":
                            [{
                                "is_select":"N",
                                "is_active":"Y"
                            }]
                    },{
                        "name":"分组管理",
                        "check_box":
                            [{
                                "is_select":"N",
                                "is_active":"Y"
                            }]
                    },{
                        "name":"属性管理",
                        "check_box":
                            [{
                                "is_select":"N",
                                "is_active":"Y"
                            }]
                    }]
                },{
                    "type":"促销管理",
                    "value":
                    [{
                        "name":"促销查询",
                        "check_box":
                            [{
                                "is_select":"N",
                                "is_active":"Y"
                            }]
                    },{
                        "name":"限时抢购",
                        "check_box":
                            [{
                                "is_select":"N",
                                "is_active":"Y"
                            }]
                    },{
                        "name":"买赠",
                        "check_box":
                            [{
                                "is_select":"N",
                                "is_active":"Y"
                            }]
                    },{
                        "name":"满减",
                        "check_box":
                            [{
                                "is_select":"N",
                                "is_active":"Y"
                            }]
                    },{
                        "name":"优惠券",
                        "check_box":
                            [{
                                "is_select":"N",
                                "is_active":"Y"
                            }]
                    },{
                        "name":"积分应用",
                        "check_box":
                            [{
                                "is_select":"N",
                                "is_active":"Y"
                            }]
                    }]
                },{
                    "type":"配置管理",
                    "value":
                    [{
                        "name":"运费模板",
                        "check_box":
                            [{
                                "is_select":"N",
                                "is_active":"Y"
                            }]
                    },{
                        "name":"物流名称管理",
                        "check_box":
                            [{
                                "is_select":"N",
                                "is_active":"Y"
                            }]
                    },{
                        "name":"支付方式",
                        "check_box":
                            [{
                                "is_select":"N",
                                "is_active":"Y"
                            }]
                    }]
                },{
                    "type":"权限管理",
                    "value":
                    [{
                        "name":"账号帮助",
                        "check_box":
                            [{
                                "is_select":"N",
                                "is_active":"Y"
                            }]
                    },{
                        "name":"角色管理",
                        "check_box":
                            [{
                                "is_select":"N",
                                "is_active":"Y"
                            }]
                    },{
                        "name":"员工管理",
                        "check_box":
                            [{
                                "is_select":"N",
                                "is_active":"Y"
                            }]
                    }]
                }]
            }]
            """
        Then jobs获取角色信息
            """
            [{
                "role_name":"角色4",
                #"button":"添加权限",
                "permissions":
                    {
                        "type":"",
                        "value":
                            [{
                                "name":"暂未给此角色添加权限"
                            }]
                    }
            }]
            """




